### ISSUE TITLE
！

### ISSUE THREAD

**Issue by pk3725069** [Healingl/Ogeek_Stopwords#1]
！！！

**Comment by Healingl** [comment]
> 求一份ogeek初赛数据 谢谢了 [lhzh2qh@163.com](mailto:lhzh2qh@163.com)

链接：https://pan.baidu.com/s/1O61ZUcov-vPEVXWPrltCQg 
提取码：s99j

**Comment by Healingl** [comment]
> 求一份ogeek初赛数据 谢谢了 [lhzh2qh@163.com](mailto:lhzh2qh@163.com)

链接：https://pan.baidu.com/s/1O61ZUcov-vPEVXWPrltCQg 
提取码：s99j
